import './globals.css'
import type { Metadata } from 'next'

import Navbar from '@/components/Navbar';
import { PostsMetadata } from '@/models/post';
import { Constants } from '@/utils/constants';
import { getPostsMetadata } from '@/utils/ServerCommon';


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const postsMetadata: PostsMetadata[] = getPostsMetadata();

  return (
    <html lang="en">

      <body
        className="flex flex-col h-screen"
        style={{ backgroundColor: Constants.mainBgColor }}
      >

        <header className="text-white text-center">
          <Navbar options={postsMetadata}/>
        </header>

        <main className="flex-1 overflow-y-auto p-5 mx-auto w-5/6">
          {children}
        </main>

      </body>
    </html>
  )
}
