import './globals.css'
import type { Metadata } from 'next'

import Navbar from '@/components/Navbar';
import { PostsMetadata } from '@/models/post';
import { Constants } from '@/utils/constants';
import { getPostsMetadata } from '@/utils/ServerCommon';


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const postsMetadata: PostsMetadata[] = getPostsMetadata();

  return (
    <html lang="en">

      <body
        className="flex flex-col h-screen"
        style={{ backgroundColor: Constants.bodyBgColor }}
      >

        <header className="text-white text-center">
          <Navbar options={postsMetadata}/>
        </header>

        <main className="overflow-y-auto ml-5 mr-10 mt-2 mb-2 h-screen">
          {children}
        </main>

        <footer className="bottom-0 w-full text-center" style={{
            backgroundColor: Constants.footerBgColor,
            color: "white",
            boxShadow: '-10px 0px 13px -7px #000000, 10px 0px 13px -7px #000000, 35px -23px 2px -16px rgba(0, 0, 0, 0)',
          }}>
          粵ICP备2023000078号
        </footer>

      </body>
    </html>
  )
}
