import type { Metadata } from 'next'

import Navbar from '@/components/Navbar';
import { PostsMetadata } from '@/models/post';
import { Constants } from '@/utils/constants';


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <main className="mx-auto ml-[8vw] mr-[8vw]">
      {children}
    </main>
  )
}
