import Image from 'next/image'
import type { Metadata } from 'next'
import * as fs from 'fs/promises';

import { getPostsMetadata } from '@/utils/ServerCommon';
import { Main } from '@/components/Main';

export const metadata: Metadata = {
  title: "Inmove",
  description: 'Generated by create next app',
}

export default async function PostHome() {
  const postsMetadata = getPostsMetadata();
  return <Main metadata={postsMetadata} />
}
